
Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/concerns/*.rb'
    - 'app/models/concerns/*.rb'

Style/EmptyMethod:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Not:
  Enabled: false

Style/AndOr:
  Enabled: false
