AllCops:
  TargetRubyVersion: 2.6.0

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Max: 400

Style/EmptyMethod:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Not:
  Enabled: false

Style/AndOr:
  Enabled: false
